function loadObj = DefineLoad()
    % Define the load as a sphere with a given radius.
    loadObj = struct( ...
        'name', 'Load1', ...
        'type', 'cylinder', ...
        'id', 1, ...
        'position', [0, 0, 0], ...  % This will be updated from the trajectory.
        'extents', [2, 5], ...      % For a cylinder: [radius, height]
        'rotations', [0, 0, 0] ...
    );
end