% List of objects for use with collision algorithm. 
% 
% Name is name returned to user when collision warning or detection is given
% 
% Type, is type of object. For now only cubes are supported.
% 
% Define position and rotation to orient the object in space. All coordinates are cartesian and rotations are tait anges (Yaw, ptich and roll).

% 'name'          - Name of object, also used as an identifyer for what to
% do during the collision detection. e.g. differentiate between different collision severity. Collision with the deck is not bad, and should give a different notification. 
% 'type'          - Type og geometric object, eg sphere, cube, sylinder
% 'id'            - Specific identifier for each object. 
% 'position'      - Cartesian coordinate for center point
% 'extents'       - Side lengths for object
% 'rotations'     - Rotation for object

function objects = ListOfObjects()
objects(1) = struct( ...
    'name', 'Main Deck', ...
    'type', 'cube', ...
    'position', [0, 0, -0.25], ...
    'extents', [15, 15, 0.5], ...
    'rotations', [0, 0, 0] ...
);

objects(2) = struct( ...
    'name', 'Crate', ...
    'type', 'cube', ...
    'position', [15, 3, 0], ...
    'extents', [6, 1, 5], ...
    'rotations', [0, 0, 0] ...
);

objects(3) = struct( ...
    'name', 'Tower', ...
    'type', 'cube', ...
    'position', [-5, -4, 2], ...
    'extents', [10, 5, 2], ...
    'rotations', [0, 0, 0] ...
);
end
