function loadObj = DefineLoad()
    % Define the load as a sphere with a given radius.
    loadObj = struct( ...
    'type', 'box', ...
    'center', [-1, 2, 0], ...
    'extents', [5, 10,5], ...
    'rotation', [0, 0, 0], ...
    'time', []...
    );
end