function objects = ListOfObjects()
% ListOfObjects returns an array of stationary objects (boxes, cylinders, and spheres).
% All objects have the fields:
%   - name: A string for the object name.
%   - type: 'box', 'cylinder', or 'sphere'.
%   - center: A 1x3 vector for the object's center.
%   - extents: For boxes and cylinders, the full dimensions (for spheres, set to [] or a placeholder).
%   - rotation: A 1x3 vector of Tait-Bryan angles (yaw, pitch, roll) in degrees.
%   - radius: For spheres (and for cylinders, radius is derived from extents).

objects(1) = struct( ...
    'name', 'Water Tank', ...
    'type', 'cylinder', ...
    'center', [3, 4, 0], ...
    'extents', [10, 30], ... 
    'rotation', [0, 0, 0] ...
);

objects(1) = struct( ...
    'name', 'Main Deck', ...
    'type', 'box', ...
    'center', [3, 2, 1], ...
    'extents', [30, 30, 1], ...   % Full extents for a box.
    'rotation', [0, 0, 0] ... % Rotation angles (in degrees).
);

objects(2) = struct( ...
    'name', 'Cargo Hold', ...
    'type', 'box', ...
    'center', [4, 0, 0], ...
    'extents', [3, 3, 1], ...
    'rotation', [0, 0,0 ] ...
);

% objects(3) = struct( ...
%     'name', 'Water Tank', ...
%     'type', 'cylinder', ...
%     'center', [8, 4, 2], ...
%     'extents', [5, 4], ...  % For a cylinder: [radius, height]
%     'rotation', [45, 45, 10] ...
% );

objects(3) = struct( ...
    'name', 'Lifeboat', ...
    'type', 'sphere', ...
    'center', [10, 8, 0], ...
    'extents', [3], ...         % Not used for spheres.
    'rotation', [0, 0, 0] ...
);

% objects(5) = struct( ...
%     'name', 'Radar Dome', ...
%     'type', 'cylinder', ...
%     'center', [-2, 4, 3], ...
%     'extents', [2, 3], ...     % For a cylinder: [radius, height]
%     'rotation', [10, 0, 0] ...
% );

objects(4) = struct( ...
    'name', 'Bridge', ...
    'type', 'box', ...
    'center', [20, 20, 10], ...
    'extents', [10, 10, 20], ...
    'rotation', [0, 0, 0] ...
);
end
