
syms
theta = sym('theta',[1, 5],'real');
thetadot = sym('thetadot',[1, 5],'real');
thetaddot = sym('thetaddot',[1, 5],'real');

phi = sym('phi',[1, 5],'real');
phidot = sym('phidot',[1, 5],'real');
phiddot = sym('phiddot',[1, 5],'real');

syms L1 L2 L3 L4 h1 d2 real

frames(1) = struct( ...
        'framenumber', [1], ...
        'rotationaxis', [3],...
        'rotationvar', [theta(1)], ...
        'rotationvardot', [thetadot(1)], ...
        'cm2joint', [0,0,h1], ...
        'joint2cm', [0,0,0], ...
        'Qcoordinates', sym([theta(1); thetadot(1); thetaddot(1)]), ...
        'mass',[],'Jmatrix',[],'Ematrix', [],'Edotmatrix', [],'Rmatrix', [],'Rdotmatrix', [],'Omatrix', [],'Bmatrix', [],'Bdotmatrix', []);

frames(2) = struct ( ...
        'framenumber', [2], ...
        'rotationaxis', [1],...
        'rotationvar', [theta(2)], ...
        'rotationvardot', [thetadot(2)], ...
        'cm2joint', [d2,0,L1-h1], ...
        'joint2cm', [0,L2/2,0], ...
        'Qcoordinates', sym([theta(2); thetadot(2); thetaddot(2)]), ...
        'mass',[],'Jmatrix',[],'Ematrix', [],'Edotmatrix', [],'Rmatrix', [],'Rdotmatrix', [],'Omatrix', [],'Bmatrix', [],'Bdotmatrix', []);

frames(3) = struct ( ...
        'framenumber', [3], ...
        'rotationaxis', [1],...
        'rotationvar', [theta(3)], ...
        'rotationvardot', [thetadot(3)], ...
        'cm2joint', [0,L2/2,0], ...
        'joint2cm', [0,L3/2,0], ...
        'Qcoordinates', sym([theta(3); thetadot(3); thetaddot(3)]), ...
        'mass',[],'Jmatrix',[],'Ematrix', [],'Edotmatrix', [],'Rmatrix', [],'Rdotmatrix', [],'Omatrix', [],'Bmatrix', [],'Bdotmatrix', []);



syms t phi phidot

subs(likning, phi, t*phidot)

diff(likning, t)

