
syms
theta = sym('theta',[1, 5],'real');
thetadot = sym('thetadot',[1, 5],'real');
thetaddot = sym('thetaddot',[1, 5],'real');

syms L1 L2 real

frames(1) = struct( ...
        'framenumber', [1], ...
        'rotationaxis', [1],...
        'rotationvar', [theta(1)], ...
        'rotationvardot', [thetadot(1)], ...
        'cm2joint', [0,0,0], ...
        'joint2cm', [0,0,L1], ...
        'Qcoordinates', sym([theta(1); thetadot(1); thetaddot(1)]), ...
        'mass',[],'Jmatrix',[],'Ematrix', [],'Edotmatrix', [],'Rmatrix', [],'Rdotmatrix', [],'Omatrix', [],'Bmatrix', [],'Bdotmatrix', []);

frames(2) = struct ( ...
        'framenumber', [2], ...
        'rotationaxis', [2],...
        'rotationvar', [theta(2)], ...
        'rotationvardot', [thetadot(2)], ...
        'cm2joint', [0,0,0], ...
        'joint2cm', [0,0,L1], ...
        'Qcoordinates', sym([theta(2); thetadot(2); thetaddot(2)]), ...
        'mass',[],'Jmatrix',[],'Ematrix', [],'Edotmatrix', [],'Rmatrix', [],'Rdotmatrix', [],'Omatrix', [],'Bmatrix', [],'Bdotmatrix', []);

frames(3) = struct ( ...
        'framenumber', [3], ...
        'rotationaxis', [1],...
        'rotationvar', [theta(3)], ...
        'rotationvardot', [thetadot(3)], ...
        'cm2joint', [0,0,0], ...
        'joint2cm', [0,0,0], ...
        'Qcoordinates', sym([theta(3); thetadot(3); thetaddot(3)]), ...
        'mass',[],'Jmatrix',[],'Ematrix', [],'Edotmatrix', [],'Rmatrix', [],'Rdotmatrix', [],'Omatrix', [],'Bmatrix', [],'Bdotmatrix', []);

B = makeB(2,frames)

O1 = makeO(1,frames)
O2 = makeO(2,frames)

E1_1 = makeErel(frames(1))
E1_2 = makeErel(frames(2))

v = E1_1(1:3,4) + E1_2(1:3,4)
unitv = sqrt(v(1)^2 + v(2)^2 + v(3)^2)
