clr
syms
theta = sym('theta',[1, 5],'real');
thetadot = sym('thetadot',[1, 5],'real');
thetaddot = sym('thetaddot',[1, 5],'real');

syms L1 L2 real

frames(1) = struct( ...
        'framenumber', [1], ...
        'rotationaxis', [3],...
        'rotationvar', [theta(1)], ...
        'rotationvardot', [thetadot(1)], ...
        'cm2joint', [0,0,0], ...
        'joint2cm', [L1/2,0,0], ...
        'Qcoordinates', sym([theta(1); thetadot(1); thetaddot(1)]), ...
        'mass',[],'Jmatrix',[],'Ematrix', [],'Edotmatrix', [],'Rmatrix', [],'Rdotmatrix', [],'Omatrix', [],'Bmatrix', [],'Bdotmatrix', []);

frames(2) = struct ( ...
        'framenumber', [2], ...
        'rotationaxis', [3],...
        'rotationvar', [theta(2)], ...
        'rotationvardot', [thetadot(2)], ...
        'cm2joint', [0,0,0], ...
        'joint2cm', [L2/2,0,0], ...
        'Qcoordinates', sym([theta(2); thetadot(2); thetaddot(2)]), ...
        'mass',[],'Jmatrix',[],'Ematrix', [],'Edotmatrix', [],'Rmatrix', [],'Rdotmatrix', [],'Omatrix', [],'Bmatrix', [],'Bdotmatrix', []);

B = makeB(2,frames)



