function F = makeFrame()
    % Initialize a frame struct
    F = struct( ...
        'framenumber', [], ...
        'rotationvar', [], ...
        'rotationvardot', [], ...
        'rotationaxis',[], ...
        'cm2joint',[0,0,0], ...
        'joint2cm',[0,0,0],...
        'Qcoordinates',sym([])); 


end