function F = makeFrame()
    % Initializes a frame struct with default values
    % Output:
    %   F - Frame struct

    F = struct( ...
        'framenumber', [], ...
        ...
        'rotationaxis', [],...
        'rotationvar', [], ...
        'rotationvardot', [], ...
        ...
        'cm2joint', [0,0,0], ...
        'joint2cm', [0,0,0], ...
        ...
        'Qcoordinates', sym([]), ...% Format Q = [theta1, thetadot1, thetaddot1; ..., ... ,... ; thetaN, thetadotN, thetaddotN], col1 = nodot, col2: dot, col3: ddot 
        ...
        'mass',[],...
        'Jmatrix',[], ...
        ...
        ...
        'Ematrix', [], ...
        'Edotmatrix', [], ...
        'Rmatrix', [], ...
        'Rdotmatrix', [], ...
        'Omatrix', [], ...
        ...
        'Bmatrix', [], ...
        'Bdotmatrix', []);
end
