% -------------------------------------------------------------------
%  Generated by MATLAB on 8-May-2025 15:55:39
%  MATLAB version: 24.2.0.2863752 (R2024b) Update 5
% -------------------------------------------------------------------
saveVarsMat = load('Reaction_3_link_8_mai_2025.mat');

reactions = saveVarsMat.reactions; % <1x1 sym> unsupported class

clear saveVarsMat;
