%% defineSystem
%{
This file defines the open looped system. The following parameters are
necessary.
        Properties:     |    Types:
        ----------------|-------------------------------
        framenumber     |   int
        rotationaxis    |   0, 1, 2, 3
        rotationvar     |   sym / constant
        cm2joint        |   1x3 vector, syms / constants
        joint2cm        |   1x3 vector, syms / constants
        initconditions  |   Nx3 vector, syms / constants    
        Qcoordinates    |   Nx3 vector, syms, Format: [theta, thetad, thetadd ; ...] for each coordinate
        Fvec            |   1x3 vector, syms / constants
        Tvec            |   1x3 vector, syms / constants
        mass            |   sym / constant
        Jmatrix         |   3x3 matrix, syms / constants

%}
clear
clc


wiresegments = 1;
wirelength = 10/wiresegments;
% Optional config filename
filename = sprintf('Crane%dEL.json', wiresegments);


%% Define symbolic variables
syms cr crd crdd trolley trolleyd trolleydd container containerd containerdd real

% Wire rotation - 3
theta = sym('theta',[1, wiresegments],'real');
thetad = sym('thetad',[1, wiresegments],'real');
thetadd = sym('thetadd',[1, wiresegments],'real');

% Wire Rotation - 1
phi = sym('phi',[1, wiresegments],'real');
phid = sym('phid',[1, wiresegments],'real');
phidd = sym('phidd',[1, wiresegments],'real');

% Wire Lengths
lambda = sym('lambda',[1, wiresegments],'real');
lambdad = sym('lambdad',[1, wiresegments],'real');
lambdadd = sym('lambdadd',[1, wiresegments],'real');

% J-matrix values [kgm^2] for wire
xxLink = 7296;      
yyLink = 7296;       
zzLink = 0.019456;   
 

%% Create Frame instances
for i = 1:(wiresegments*3 + 3)
    frames(i) = Frame('framenumber',i);
end

%% Define Frame Properties
% Crane Boom %%%%%%%%%%%%%%%%%%%%%%%%%%%%
frames(1).setProperties('Qcoordinates', [cr crd crdd], 'initconditions', [0,0,0], ...
    'rotationaxis', 3, 'rotationvar', cr, ...
    'cm2joint',[0,0,0],'joint2cm',[4.68, 0.61, 4.93], ...
    'mass', 147000, 'Jmatrix', [1.6701e6,  3.6194e5, -1.6755e6; 3.6194e5,  1.2872e7,  1.9375e3; -1.6755e6,  1.9375e3,  1.2143e7], ...
    'Fvec', [0,0,-9.81*147000], 'Tvec', [0,0,0])

% Trolley %%%%%%%%%%%%%%%%%%%%%%%%%%%%
frames(2).setProperties('Qcoordinates', [trolley, trolleyd, trolleydd], 'initconditions', [0,0,0], ...
    'rotationaxis', 0, 'rotationvar', 0, ...
    'cm2joint', [0,-0.61,7.00],'joint2cm', [trolley, 0,0], ...
    'mass', 16800,'Jmatrix', [1.4080e4, -3.0649e3,  2.7903e2; -3.0649e3,  3.2480e4,  7.1065e0; 2.7903e2,  7.1065e0,  2.7601e4], ...
    'Fvec', [0,0,-9.81*16800], 'Tvec', [0,0,0]);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if wiresegments >= 1
    % Wiresegment 1, 3-axis
    frames(3).setProperties('Qcoordinates', [theta(1),thetad(1),thetadd(1)], 'initconditions', [0,0,0], ...
        'rotationaxis', 3, 'rotationvar', theta(1), ...
        'cm2joint', [0,0,0], 'joint2cm',[0,0,0], ...
        'mass', 0, 'Jmatrix', [0,0,0; 0,0,0; 0,0,0], ...
        'Fvec', [0,0,0], 'Tvec', [0,0,0])

    % Wiresegment 1, 1-axis
    frames(4).setProperties('Qcoordinates', [phi(1),phid(1),phidd(1)], 'initconditions', [0,0,0], ...
        'rotationaxis', 1, 'rotationvar', phi(1), ...
        'cm2joint', [0,0,0], 'joint2cm',[0,0,0], ...
        'mass', 0, 'Jmatrix', [0,0,0; 0,0,0; 0,0,0], ...
        'Fvec', [0,0,0], 'Tvec', [0,0,0])

    % Wiresegment 1, extension
    frames(5).setProperties('Qcoordinates', [lambda(1),lambdad(1),lambdadd(1)], 'initconditions', [-wirelength,0,0], ...
        'rotationaxis', 0, 'rotationvar', 0, ...
        'cm2joint', [0,0,0], 'joint2cm',[0,0,lambda(1)/2], ...
        'mass', 254, 'Jmatrix', [xxLink,0,0; 0,yyLink,0; 0,0,zzLink], ...
        'Fvec', [0,0,-9.81*254], 'Tvec', [0,0,0])
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if wiresegments >= 2
    % Wiresegment 2, 3-axis
    frames(6).setProperties('Qcoordinates', [theta(2),thetad(2),thetadd(2);lambda(1),lambdad(1),lambdadd(1)], 'initconditions', [0,0,0], ...
        'rotationaxis', 3, 'rotationvar', theta(2), ...
        'cm2joint', [0,0,lambda(1)/2], 'joint2cm',[0,0,0], ...
        'mass', 0, 'Jmatrix', [0,0,0; 0,0,0; 0,0,0], ...
        'Fvec', [0,0,0], 'Tvec', [0,0,0])

    % Wiresegment 2, 1-axis
    frames(7).setProperties('Qcoordinates', [phi(2),phid(2),phidd(2)], 'initconditions', [0,0,0], ...
        'rotationaxis', 1, 'rotationvar', phi(2), ...
        'cm2joint', [0,0,0], 'joint2cm',[0,0,0], ...
        'mass', 0, 'Jmatrix', [0,0,0; 0,0,0; 0,0,0], ...
        'Fvec', [0,0,0], 'Tvec', [0,0,0])

    % Wiresegment 2, extension
    frames(8).setProperties('Qcoordinates', [lambda(2),lambdad(2),lambdadd(2)], 'initconditions', [-wirelength,0,0], ...
        'rotationaxis', 0, 'rotationvar', 0, ...
        'cm2joint', [0,0,0], 'joint2cm',[0,0,lambda(2)/2], ...
        'mass', 254, 'Jmatrix', [xxLink,0,0; 0,yyLink,0; 0,0,zzLink], ...
        'Fvec', [0,0,-9.81*254], 'Tvec', [0,0,0])

end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if wiresegments >= 3
    % Wiresegment 3, 3-axis
    frames(9).setProperties('Qcoordinates', [theta(3),thetad(3),thetadd(3);lambda(2),lambdad(2),lambdadd(2)], 'initconditions', [0,0,0], ...
        'rotationaxis', 3, 'rotationvar', theta(3), ...
        'cm2joint', [0,0,lambda(2)/2], 'joint2cm',[0,0,0], ...
        'mass', 0, 'Jmatrix', [0,0,0; 0,0,0; 0,0,0], ...
        'Fvec', [0,0,0], 'Tvec', [0,0,0])

    % Wiresegment 3, 1-axis
    frames(10).setProperties('Qcoordinates', [phi(3),phid(3),phidd(3)], 'initconditions', [0,0,0], ...
        'rotationaxis', 1, 'rotationvar', phi(3), ...
        'cm2joint', [0,0,0], 'joint2cm',[0,0,0], ...
        'mass', 0, 'Jmatrix', [0,0,0; 0,0,0; 0,0,0], ...
        'Fvec', [0,0,0], 'Tvec', [0,0,0])

    % Wiresegment 3, extension
    frames(11).setProperties('Qcoordinates', [lambda(3),lambdad(3),lambdadd(3)], 'initconditions', [-wirelength,0,0], ...
        'rotationaxis', 0, 'rotationvar', 0, ...
        'cm2joint', [0,0,0], 'joint2cm',[0,0,lambda(3)/2], ...
        'mass', 254, 'Jmatrix', [xxLink,0,0; 0,yyLink,0; 0,0,zzLink], ...
        'Fvec', [0,0,-9.81*254], 'Tvec', [0,0,0])

end

% Container %%%%%%%%%%%%%%%%%%%%%%%%%%%%
lastframe = length(frames);
frames(lastframe).setProperties('Qcoordinates', [container, containerd, containerdd;lambda(wiresegments),lambdad(wiresegments),lambdadd(wiresegments)], 'initconditions', [0,0,0],...
    'rotationaxis', 3, 'rotationvar', container, ...
    'cm2joint',[0,0,lambda(wiresegments)/2],'joint2cm',[0,0, -1.5], ...
    'mass', 5000, 'Jmatrix', [7500,  0, 0; 0,  7500,  0; 0,  0,  7500], ...
    'Fvec', [0,0,-9.81*5000], 'Tvec', [0,0,0])

