%% This script substitutes the values from a .csv file into the reaction forces for a 3-link system without elongation of the wire. This is a test

syms theta1 thetadot1 thetaddot1 ...
      theta2 thetadot2 thetaddot2 ...
      theta3 thetadot3 thetaddot3 ...
      theta4 thetadot4 thetaddot4 ...
      theta5 thetadot5 thetaddot5 ...
      theta6 thetadot6 thetaddot6 ...
      theta7 thetadot7 thetaddot7 ...
      theta8 thetadot8 thetaddot8 real

Reaction_Only_3_links(frames);

% Read the CSV file
data = readmatrix('Q_history_fixedlength.csv');

% Loop over each row and substitute values into the symbolic expression
numSteps = size(data, 1);

reactionForces = zeros(numSteps, 16);

for i = 1:numSteps
    % Get the actual time from the CSV (column 2)
    t = data(i, 2);
    
    % Perform the substitution for this time step using columns 3 to 26
    result = double( subs(Reaction_Only_3_links(frames), ...
        {theta1, thetadot1, thetaddot1, ...
         theta2, thetadot2, thetaddot2, ...
         theta3, thetadot3, thetaddot3, ...
         theta4, thetadot4, thetaddot4, ...
         theta5, thetadot5, thetaddot5, ...
         theta6, thetadot6, thetaddot6, ...
         theta7, thetadot7, thetaddot7, ...
         theta8, thetadot8, thetaddot8}, ...
        {data(i, 3), data(i, 4), data(i, 5), ...
         data(i, 6), data(i, 7), data(i, 8), ...
         data(i, 9), data(i,10), data(i,11), ...
         data(i,12), data(i,13), data(i,14), ...
         data(i,15), data(i,16), data(i,17), ...
         data(i,18), data(i,19), data(i,20), ...
         data(i,21), data(i,22), data(i,23), ...
         data(i,24), data(i,25), data(i,26)}));
    
    % Store the time in the first column and the reaction forces in the rest
    reactionForces(i, 1) = t;
    reactionForces(i, 2:end) = result;
end